### ISSUE TITLE
Create Documentation for Creating Token and NFT Tutorial

### ISSUE THREAD

**Issue by arg-foo** [AElfProject/aelf-learn#8]
Create a documentation to teach developers how to create their own token and nft collection.

- [ ] Introduce SEED Faucet
- [ ] Tutorial on creating Token
- [ ] Tutorial on issuing Token
- [x] Tutorial on creating NFT Collection
- [ ] Tutorial on issuing NFTs

**Comment by vasmohi** [comment]
Moving to aelf Research and docs project from Dapp factory
